"""
backend/app/schemas.py
=======================
Pydantic v2 request / response schemas with strict validation.

PredictionRequest mirrors the feature columns in ml/config.py.
Validation errors produce clear 422 messages that the frontend
can display directly to the user.
"""

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

# ---------------------------------------------------------------------------
# Allowed literal types (duplicated from ml/config — backend is a separate
# deployable so we keep it self-contained; values must stay in sync manually
# or by importing config if deployed as a monorepo).
# ---------------------------------------------------------------------------

StressLevel  = Literal["Low", "Medium", "High"]
CountryName  = Literal[
    "India", "USA", "UK", "Canada", "Australia",
    "Germany", "Brazil", "Japan", "South Korea", "Other",
]
PlatformName = Literal[
    "Instagram", "Twitter", "Facebook", "TikTok",
    "YouTube", "Reddit", "LinkedIn", "None",
]


# ---------------------------------------------------------------------------
# Request schema
# ---------------------------------------------------------------------------

class PredictionRequest(BaseModel):
    """
    Lifestyle and behavioural inputs for the mental health score predictor.

    All values are validated against realistic human ranges.
    The API will return a 422 with a clear message for any invalid field.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        json_schema_extra={
            "example": {
                "Physical_Activity_Hours": 1.5,
                "Sleep_Hours": 7.0,
                "Screen_Time_Hours": 4.0,
                "Stress_Level": "Medium",
                "Country": "India",
                "Platform": "Instagram",
            }
        },
    )

    Physical_Activity_Hours: Annotated[
        float,
        Field(ge=0.0, le=10.0, description="Hours of physical activity per day (0–10)"),
    ]
    Sleep_Hours: Annotated[
        float,
        Field(ge=0.0, le=12.0, description="Hours of sleep per night (0–12)"),
    ]
    Screen_Time_Hours: Annotated[
        float,
        Field(ge=0.0, le=16.0, description="Hours of screen time per day (0–16)"),
    ]
    Stress_Level: StressLevel = Field(
        description="Self-reported stress level: Low, Medium, or High"
    )
    Country: CountryName = Field(
        description="Country of residence"
    )
    Platform: PlatformName = Field(
        description="Primary social-media platform used daily"
    )

    @field_validator("Physical_Activity_Hours", "Sleep_Hours", "Screen_Time_Hours")
    @classmethod
    def no_nan(cls, v: float) -> float:
        import math
        if math.isnan(v) or math.isinf(v):
            raise ValueError("Value must be a finite number.")
        return round(v, 4)


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------

class PredictionResponse(BaseModel):
    """Score prediction response returned by POST /predict."""

    prediction_id: UUID = Field(description="Unique ID for this prediction request")
    mental_health_score: float = Field(
        description="Estimated mental health score 0–100 (higher = better wellness)",
        ge=0.0, le=100.0,
    )
    status_flag: str  = Field(description="Band label, e.g. 'Good', 'Moderate'")
    message:     str  = Field(description="Short supportive message")
    disclaimer:  str  = Field(
        description="Reminder that this is an informational tool, not a diagnosis"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "prediction_id": "550e8400-e29b-41d4-a716-446655440000",
                "mental_health_score": 67.5,
                "status_flag": "Good",
                "message": "You're doing well. Small, consistent habits will keep you here.",
                "disclaimer": (
                    "This score is generated by a machine-learning model trained on "
                    "synthetic data. It is NOT a medical diagnosis. Please consult a "
                    "qualified mental health professional for any concerns."
                ),
            }
        }
    )


class HealthResponse(BaseModel):
    status:       str
    model_loaded: bool
    version:      str


class ModelInfoResponse(BaseModel):
    model_name:    str
    training_date: str
    metrics:       dict
    is_synthetic:  bool
    data_warning:  str | None = None
